{% set version = "8.2.10" %}

package:
  name: gnureadline
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gnureadline/gnureadline-{{ version }}.tar.gz
  md5: b0c597a2dd32b629e7fa4c0a15ff764d

build:
  number: 1
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - gnureadline
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ludwigschwardt/python-gnureadline
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: The standard Python readline extension statically linked against the GNU readline library

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
