{% set version = "6.3.8" %}

package:
    name: gnureadline
    version: {{ version }}

source:
    fn: gnureadline-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/g/gnureadline/gnureadline-{{ version }}.tar.gz
    md5: ba341f4b907250bd1f47dbc06290604f

build:
    number: 1000
    skip: True  # [not osx]
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
  imports:
      - gnureadline

about:
    home: http://github.com/ludwigschwardt/python-gnureadline
    license: GPL-3.0
    summary: The standard Python readline extension statically linked against the GNU readline library

extra:
    recipe-maintainers:
        - ocefpaf
        - scopatz
