# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aXzKxkn/tPA5+WT4A5zR+Z/PRqnRBrlZigof2qc6//0yY4R3PX2tlan/Oe9qJzgG2tyVu1njyZ2ON6HXTXGZEsKkHGQK5VarhXrgju7Oe84j4UKsMpqKMnDeeVOp9xC9ZIKNOPvxYlxRVrY7eMfaApZsBKFk0GFNs5JyVW4azfCjDGGUd4TdBpsYzl4nhYKwlIrbc+vOPGO4Sz6fLK6m+VBwiPh6J97rJZYss8dKMP2ovpr6nxlmJBxfKXWIaTaD2fYYQjS1+jQ+bqTZ7POSGDnen+se9EWxWMUL7Y35J4XbbcDY/aZuXiLDyR/j2tL+ZYd0XesW/Aig/JvrG+mwf+tznNGkaqGiE9Kl0TL4888UUdg7vXcDZshsU3gEgt0WR3SOgxnj+8gOxic3ALUZ9cA6Vo0VyCVqJHh6zDE9sCuWbT8cD+DwcAkWmU64GqTRZq79umy/Pez2gwNJcjQFr0ak8e5MgE51Q7iuUHsOqrJ8lqZxu/fmS6JXqHls54C9jidjwnTsw5NfLAQzBBQFIyctOei65dtqEF0Vw2JxJxStcl5Xi220Grj1s15UbAIHS0H1GD/4Xbfurxk5L0ISnai2Wthb7bMhnKq9JqWKZU6DMdUfqnZKQTWy9+mvkGdEe41536e3QnOmQIAm/BHGdEz5UHVqoai7VYTWOmbH33Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
