travis:
  secure:
    BINSTAR_TOKEN: aXzKxkn/tPA5+WT4A5zR+Z/PRqnRBrlZigof2qc6//0yY4R3PX2tlan/Oe9qJzgG2tyVu1njyZ2ON6HXTXGZEsKkHGQK5VarhXrgju7Oe84j4UKsMpqKMnDeeVOp9xC9ZIKNOPvxYlxRVrY7eMfaApZsBKFk0GFNs5JyVW4azfCjDGGUd4TdBpsYzl4nhYKwlIrbc+vOPGO4Sz6fLK6m+VBwiPh6J97rJZYss8dKMP2ovpr6nxlmJBxfKXWIaTaD2fYYQjS1+jQ+bqTZ7POSGDnen+se9EWxWMUL7Y35J4XbbcDY/aZuXiLDyR/j2tL+ZYd0XesW/Aig/JvrG+mwf+tznNGkaqGiE9Kl0TL4888UUdg7vXcDZshsU3gEgt0WR3SOgxnj+8gOxic3ALUZ9cA6Vo0VyCVqJHh6zDE9sCuWbT8cD+DwcAkWmU64GqTRZq79umy/Pez2gwNJcjQFr0ak8e5MgE51Q7iuUHsOqrJ8lqZxu/fmS6JXqHls54C9jidjwnTsw5NfLAQzBBQFIyctOei65dtqEF0Vw2JxJxStcl5Xi220Grj1s15UbAIHS0H1GD/4Xbfurxk5L0ISnai2Wthb7bMhnKq9JqWKZU6DMdUfqnZKQTWy9+mvkGdEe41536e3QnOmQIAm/BHGdEz5UHVqoai7VYTWOmbH33Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
