travis:
  secure:
    BINSTAR_TOKEN: xxHxBKSc/kkeVWkb+ZIdevVWjoOxnI0SZYuo0pQGKcDEvpwoIKe7xIoW4MuT17I63oi2Bqc3VcxNldoCtbs5sF9fiYxlknmf4tSMfYgroXS7FP8T76rM2sCxNTg1OQAGHF02iqAZ5LiPR4aMen0NVjEcxuKT0UbN+Z7a07bh+WHA9XtUK0y7FKK1rSpylRP2apm6osnM9l72rq68qNPK5xxDv77J7mX0R9sHwvZgUQCHwDu8IMNQ8sDzw/WkKMHltA24BvOq+hAyM6z2L8U1303Vwd9xCihJ9tRob5Qvm0ZDR9dh13q6cXtIGbliVcx/9guP2UcA0go0WLvLROtUkT6LpFxvlX1qhSmW3xd1dzhoU/94uC37HBGHYW+wX1X9E707OP0W10mbcl4A+g4yqE8k7N3GXvjMGBaAHjpJ/MDH48ANxNGTg2bgLYwH7PbbCCvmxduZIhvJaV19P6ecV+P16wm/DsdyQBb7+cdxfuMVMTakdtz898Vk/Mc24Ajn76ygE3kYIXrqlkTs/urs7TVkogftFu2YaqnTjXaujAWaDlq1PMIbVNIEIDIb3dij+XS1ZNu37tYUKi/4GpoROsLeBIUxVxXe6uH1vQvuqlJxo9mtuJNDW8zEQQZIpkME3DX5UwJvu85wy8Rz/7aFH6lLSgoYLNiWX9XVDzww0Og=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
